/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-04-25 17:55:28 UTC)
 * on 2013-04-26 at 21:16:13 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.contact;

/**
 * Service definition for Contact (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ContactRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Contact extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION == 14,
        "You are currently running with version %s of google-api-client. " +
        "You need version 1.14 of google-api-client to run version " +
        "1.14.2-beta of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://geekfinder2.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "contact/v1/contacts/sendemail/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Contact(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Contact(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the Contacts collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Contact contact = new Contact(...);}
   *   {@code Contact.Contacts.List request = contact.contacts().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public Contacts contacts() {
    return new Contacts();
  }

  /**
   * The "contacts" collection of methods.
   */
  public class Contacts {

    /**
     * Create a request for the method "contacts.sendEmail".
     *
     * This request holds the parameters needed by the the contact server.  After setting any optional
     * parameters, call the {@link SendEmail#execute()} method to invoke the remote operation.
     *
     * @param emailAddress
     * @return the request
     */
    public SendEmail sendEmail(java.lang.String emailAddress) throws java.io.IOException {
      SendEmail result = new SendEmail(emailAddress);
      initialize(result);
      return result;
    }

    public class SendEmail extends ContactRequest<Void> {

      private static final String REST_PATH = "{emailAddress}";

      /**
       * Create a request for the method "contacts.sendEmail".
       *
       * This request holds the parameters needed by the the contact server.  After setting any optional
       * parameters, call the {@link SendEmail#execute()} method to invoke the remote operation. <p>
       * {@link
       * SendEmail#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param emailAddress
       * @since 1.13
       */
      protected SendEmail(java.lang.String emailAddress) {
        super(Contact.this, "POST", REST_PATH, null, Void.class);
        this.emailAddress = com.google.api.client.util.Preconditions.checkNotNull(emailAddress, "Required parameter emailAddress must be specified.");
      }

      @Override
      public SendEmail setAlt(java.lang.String alt) {
        return (SendEmail) super.setAlt(alt);
      }

      @Override
      public SendEmail setFields(java.lang.String fields) {
        return (SendEmail) super.setFields(fields);
      }

      @Override
      public SendEmail setKey(java.lang.String key) {
        return (SendEmail) super.setKey(key);
      }

      @Override
      public SendEmail setOauthToken(java.lang.String oauthToken) {
        return (SendEmail) super.setOauthToken(oauthToken);
      }

      @Override
      public SendEmail setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (SendEmail) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public SendEmail setQuotaUser(java.lang.String quotaUser) {
        return (SendEmail) super.setQuotaUser(quotaUser);
      }

      @Override
      public SendEmail setUserIp(java.lang.String userIp) {
        return (SendEmail) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String emailAddress;

      /**

       */
      public java.lang.String getEmailAddress() {
        return emailAddress;
      }

      public SendEmail setEmailAddress(java.lang.String emailAddress) {
        this.emailAddress = emailAddress;
        return this;
      }

      @Override
      public SendEmail set(String parameterName, Object value) {
        return (SendEmail) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Contact}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Contact}. */
    @Override
    public Contact build() {
      return new Contact(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ContactRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setContactRequestInitializer(
        ContactRequestInitializer contactRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(contactRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
